 eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defeaultZone: http://localhost:8761/eureka/
        instance:
          hostname: localhost
